### ISSUE TITLE
Create postgres data with PK as UUID

### ISSUE THREAD

**Issue by wan54** [prismagraphql/prisma#2447]
# Bug Report

**Current behavior**

My tables in postgres are all using UUID type for their IDs. After introspected and deployed to prismagraphql/prisma:1.8 and from the playground run the mutation to create a new record I get the following error:

```
org.postgresql.util.PSQLException: ERROR: column "id" is of type uuid but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 92
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at com.prisma.api.connector.postgresql.database.PostgresApiDatabaseMutationBuilder.$anonfun$createDataItem$1(PostgresApiDatabaseMutationBuilder.scala:50)
	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
	at slick.dbio.DBIOAction$$anon$1.$anonfun$run$1(DBIOAction.scala:187)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:187)
	at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:184)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior?**

Record with PK as UUID be successfully created in PostgreSQL

**Comment by marktani** [comment]
This is part of the `1.11.0-beta`: https://github.com/prismagraphql/prisma/releases/tag/1.11.0-beta. [Here](https://www.prisma.io/docs/reference/prisma-servers-and-dbs/prisma-servers/overview-eu2ood0she#installing-prisma-beta) is more information about setting up the beta version.

**Comment by do4gr** [comment]
This feature is available in stable now.
