### ISSUE TITLE
Postgresql where with UUID id throws "org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = character varying"

### ISSUE THREAD

**Issue by jkelin** [prismagraphql/prisma#2503]
# Bug Report

Prisma version: 1.9-beta, same issue observed in 1.8

**Current behavior**
I have my database generated and Prisma running and successfully deployed.
When I attempt to select from `User` table with a `user(where: { id: "c3917b5b-18ed-4a84-a6f7-6be7a8c21d66" })` query, I get the following error

**Query request**

```
{
  users {
    id
  }
  user(where: { id: "c3917b5b-18ed-4a84-a6f7-6be7a8c21d66" }) {
    id
  }
}
```

**Query response**

```
{
  "data": {
    "users": [
      {
        "id": "c3917b5b-18ed-4a84-a6f7-6be7a8c21d66"
      }
    ],
    "user": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:cjhji0d2v000f07245jw0cxz3",
      "path": [
        "user"
      ],
      "locations": [
        {
          "line": 5,
          "column": 3
        }
      ],
      "requestId": "local:api:cjhji0d2v000f07245jw0cxz3"
    }
  ]
}
```

**Error from docker-compose logs**
```
prisma_1  | org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = character varying
prisma_1  |   Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
prisma_1  |   Position: 46
prisma_1  |     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
prisma_1  |     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
prisma_1  |     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
prisma_1  |     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
prisma_1  |     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
prisma_1  |     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
prisma_1  |     at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
prisma_1  |     at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
prisma_1  |     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
prisma_1  |     at com.prisma.api.connector.postgresql.database.PostgresApiDatabaseQueryBuilder.$anonfun$batchSelectFromModelByUnique$1(PostgresApiDatabaseQueryBuilder.scala:159)
prisma_1  |     at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
prisma_1  |     at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
prisma_1  |     at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
prisma_1  |     at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
prisma_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1  |     at java.lang.Thread.run(Thread.java:748)
prisma_1  | {"key":"error/unhandled","requestId":"local:api:cjhji0d2v000f07245jw0cxz3","clientId":"default$default","payload":{"exception":"org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = character varying\n  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.\n  Position:
46","query":"{\n  users {\n    id\n  }\n  user(where: {id: \"c3917b5b-18ed-4a84-a6f7-6be7a8c21d66\"}) {\n    id\n  }\n}\n","variables":"{\"id\":\"c3917b5b-18ed-4a84-a6f7-6be7a8c21d66\"}","code":"0","stack_trace":"org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)\\n org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)\\n org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)\\n org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)\\n org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)\\n org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)\\n org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)\\n com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)\\n com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)\\n com.prisma.api.connector.postgresql.database.PostgresApiDatabaseQueryBuilder.$anonfun$batchSelectFromModelByUnique$1(PostgresApiDatabaseQueryBuilder.scala:159)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)\\n java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n java.lang.Thread.run(Thread.java:748)","message":"ERROR: operator does not exist: uuid = character varying\n  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.\n  Position: 46"}}
prisma_1  | [Bugsnag - local / testing] Error report: com.bugsnag.Report@62c16d13
prisma_1  | org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = character varying
prisma_1  |   Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
prisma_1  |   Position: 46
prisma_1  |     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
prisma_1  |     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
prisma_1  |     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
prisma_1  |     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
prisma_1  |     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
prisma_1  |     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
prisma_1  |     at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
prisma_1  |     at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
prisma_1  |     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
prisma_1  |     at com.prisma.api.connector.postgresql.database.PostgresApiDatabaseQueryBuilder.$anonfun$batchSelectFromModelByUnique$1(PostgresApiDatabaseQueryBuilder.scala:159)
prisma_1  |     at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
prisma_1  |     at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
prisma_1  |     at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
prisma_1  |     at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
prisma_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1  |     at java.lang.Thread.run(Thread.java:748)
```

**User table datamodel**
```
type User @pgTable(name: "User") {
  id: ID! @unique @pgColumn(name:"UserId")
  DisplayName: String!
  Email: String!
  IsEmailVerified: Boolean!
  UserId: String!
}
```

**User table SQL**
```
CREATE TABLE public."User"
(
    "UserId" uuid NOT NULL,
    "DisplayName" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "IsEmailVerified" boolean NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("UserId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
```

**Comment by jkelin** [comment]
This is still an issue

**Comment by marktani** [comment]
Hey @jkelin, UUID support is part of the `1.11.0-beta`: https://github.com/prismagraphql/prisma/releases/tag/1.11.0-beta. [Here](https://www.prisma.io/docs/reference/prisma-servers-and-dbs/prisma-servers/overview-eu2ood0she#installing-prisma-beta) is more information about setting up the beta version.

**Comment by jkelin** [comment]
Installing newest beta seems to have fixed the issue, closing.

**Comment by marktani** [comment]
`1.11` was released as the stable version yesterday, so this should also work on stable 🙂
