### ISSUE TITLE
db.mutation ignore args passed from server resolvers

### ISSUE THREAD

**Issue by psycura** [prismagraphql/prisma#2547]
# Bug Report
Hello guys, and thanks for this awesome tool.

I`m trying to spin yoga-server with Prisma local cluster (Docker Postgres), and have strange issue with my custom resolver.
[Git](https://github.com/psycura/prisma-server) with project

**Current behavior**
I call mutation `createManager()` on server (`src/resolvers/Users`) with some args, and after some manipulation with data,  call to `ctx.db.mutation.createUser()` with new args
And looks like  `db.mutation.createUser()` method doesnt use args that i pass to him, but use original args that comes to `createManager().` i think so because i receive an error:

> Error: Field UserCreateInput.uid of required type String! was not provided.
> 
> GraphQL request (2:23)
> 1: mutation createManager {
> 2:   createManager(data: {email: "test1@mail.com", address: "my Addres", password: "1234556", firstName: "Test1", lastName: "Tester1", phone: "0544444444"}) {
>                          ^
> 3:     id
> ,Field "password" is not defined by type UserCreateInput.
> 
> GraphQL request (2:71)
> 1: mutation createManager {
> 2:   createManager(data: {email: "test1@mail.com", address: "my Addres", password: "1234556", firstName: "Test1", lastName: "Tester1", phone: "0544444444"}) {
>                                                                          ^
> 3:     id
> 
>     at asErrorInstance (D:\Sites\training\cbm-prisma-server\node_modules\graphql\execution\execute.js:541:43)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

**Reproduction**
Clone the [repo](https://github.com/psycura/prisma-server), 
deploy prisma on cluster
try to make mutation:
```
mutation createManager {
 createManager(data:{
    email: "test1@mail.com",
    address: "my Addres",
    password: "1234556",
    firstName: "Test1",
    lastName: "Tester1",
    phone: "0544444444"
}){
  id
}
}
```

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**
Expect that `db.mutation.createUser()` will use new args that i pass to him, and not the original one, that came to the` createManager()`

**Comment by psycura** [comment]
My fault, forgot to wrap the data into the data:{} object
Closing this issue
