### ISSUE TITLE
Upgrade to 1.8.4 resulting in addProject management@default error

### ISSUE THREAD

**Issue by roycclu** [prismagraphql/prisma#2567]
# Bug Report

**Current behavior**
prisma deploy fails

After upgrade, prisma deploy now results in `Project Not Found ‘management@default’` error.

From the full log (posted below) it looks like prisma first queries for the project, finds it, and then attempts to add a project of the same name and stage. Now why would it do that?

```
➜ timepop-service git:(feature/notificationService) prisma deploy --interactive
config CWD /Users/roycclu/TimepopRepo/timepop-service +0ms
config HOME /Users/roycclu +2ms
config definitionDir /Users/roycclu/TimepopRepo/timepop-service +1ms
config definitionPath /Users/roycclu/TimepopRepo/timepop-service/prisma.yml +0ms
cli { isGlobal: true } +0ms
StatusChecker setting status checker +0ms
cli command id deploy +6ms
cli:plugincache Got plugin from cache +0ms
cli:plugincache /Users/roycclu/Library/Caches/prisma/plugins.json +0ms
cli:plugincache Got plugin from cache +1ms
cli:plugincache /Users/roycclu/Library/Caches/prisma/plugins.json +0ms
plugins findCommand prisma-cli-core +0ms
plugin requiring command +0ms
cli-engine:plugins:manager requiring /usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core +0ms
portfinder:defaultHosts exports._defaultHosts is: [ ‘0.0.0.0’, ‘127.0.0.1’, ‘::1’, ‘fe80::1’, ‘192.168.1.4’, ‘fe80::b0b6:5eff:fe2d:363’, ‘fe80::8dab:a618:90af:b492’, ‘fdc2:e6bf:b194:befa:8dab:a618:90af:b492’, ‘fe80::56fd:24c9:1989:4073’, ‘fe80::3cf7:677b:3021:423’ ] +0ms
cli-engine:plugins:manager required +531ms
plugin required command +534ms
StatusChecker setting status checker +1s
client Initializing cluster client +0ms
Environment saving global rc +0ms
deploy checking verions +2s
deploy checking if project exists +628ms
client Sending query to cluster timepop-rds-aws +1s
client https://timepop-rds-aws_timepop.prisma.sh/management +0ms
client
client query($name: String! $stage: String!) {
client project(name: $name stage: $stage) {
client name
client stage
client }
client }
client +0ms
client { name: ‘timepop-service’, stage: ‘dev’ } +0ms
deploy adding project +515ms

Creating stage dev for service timepop-service… client Sending query to cluster timepop-rds-aws +515ms
client https://timepop-rds-aws_timepop.prisma.sh/management +0ms
client mutation addProject($name: String! $stage: String! $secrets: [String!]) {
client addProject(input: {
client name: $name,
client stage: $stage
client secrets: $secrets
client }) {
client project {
client name
client }
client }
client }
client +0ms
client { name: ‘timepop-service’,
client stage: ‘dev’,
client secrets: [ ‘mysecret123’ ] } +0ms
!
Error: Project not found: ‘management@default’: {“response”:{“errors”:[{“message”:“Project not found: ‘management@default’”,“code”:3016,“requestId”:“timepop-rds-aws_timepop:api:cjhwmdssp0dob0999s6uazapn”}],“status”:200},“request”:{“query”:" mutation addProject($name: String! $stage: String! $secrets: [String!]) {\n addProject(input: {\n name: $name,\n stage: $stage\n secrets: $secrets\n }) {\n project {\n name\n }\n }\n }\n ",“variables”:{“name”:“timepop-service”,“stage”:“dev”,“secrets”:[“mysecret123”]}}}
at GraphQLClient. (/usr/local/lib/node_modules/prisma/node_modules/graphql-request/src/index.ts:72:13)
at step (/usr/local/lib/node_modules/prisma/node_modules/graphql-request/dist/src/index.js:40:23)
at Object.next (/usr/local/lib/node_modules/prisma/node_modules/graphql-request/dist/src/index.js:21:53)
at fulfilled (/usr/local/lib/node_modules/prisma/node_modules/graphql-request/dist/src/index.js:12:58)
at 
at process._tickCallback (internal/process/next_tick.js:118:7)
util timed out +0ms
Exiting with code: 0
```

**Expected behavior?**
deployment works after prisma upgrade

my CLI version is 1.8.3
my cluster version is 1.8.4

**Comment by marktani** [comment]
How does your `prisma.yml` file look like? 🙂
Do you have a `~/.prisma/config.yml` file?

Please remove any sensitive information before sharing these files.

**Comment by roycclu** [comment]
Hi @marktani 

the prisma.yml file looks like below, and it sits in our project root 
```
datamodel: database/datamodel.graphql

seed:
  import: database/seed.graphql

secret: ${env:PRISMA_SECRET}

#== such as https://<cluster>_<workspace>.prisma.sh/<service>/dev "
endpoint: ${env:PRISMA_ENDPOINT}

hooks:
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema --project prisma
    - graphql prepare

```
Our ~/.prisma/config.yml file looks like below:

```
cloudSessionKey: >-
 <key>
clusters:
  local:
    host: 'http://localhost:4466'
```

So what's going on here? Looks like the config.yml is missing our cluster information; how do we add it back?

**Comment by marktani** [comment]
This was a specific issue for your Prisma server and is now resolved. Thanks for bringing this up!

**Comment by roycclu** [comment]
@marktani problem still exists.

**Comment by marktani** [comment]
I reached out in the support chat to further discuss this 🙂
