### ISSUE TITLE
Postgres Error (column "data_length" does not exist at character 39)

### ISSUE THREAD

**Issue by calummoore** [prismagraphql/prisma#2591]
# Bug Report

**Current behavior**
Error a short while after starting the server, which causes the client to disconnect. The server can be re-connected to (without having to restart it), but it will again disconnect after ~5 mins.

```
Calums-MacBook-Pro-2:server calummoore$ docker-compose down -v
Removing server_prisma_1   ... done
Removing server_postgres_1 ... done
Removing server_redis_1    ... done
Removing network server_default
Removing volume server_postgres
Removing volume server_redis-data
Calums-MacBook-Pro-2:server calummoore$ docker-compose up
Creating network "server_default" with the default driver
Creating volume "server_postgres" with default driver
Creating volume "server_redis-data" with default driver
Creating server_redis_1    ... done
Creating server_prisma_1   ... done
Creating server_postgres_1 ... done
Attaching to server_postgres_1, server_redis_1, server_prisma_1
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
redis_1     | 1:C 07 Jun 14:58:47.925 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 07 Jun 14:58:47.925 # Redis version=4.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 07 Jun 14:58:47.925 # Configuration loaded
redis_1     | 1:M 07 Jun 14:58:47.945 * Running mode=standalone, port=6379.
redis_1     | 1:M 07 Jun 14:58:47.945 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 07 Jun 14:58:47.945 # Server initialized
postgres_1  | selecting dynamic shared memory implementation ... posix
redis_1     | 1:M 07 Jun 14:58:47.945 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 07 Jun 14:58:47.946 * Ready to accept connections
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | performing post-bootstrap initialization ... ok
postgres_1  | syncing data to disk ... ok
postgres_1  |
postgres_1  | Success. You can now start the database server using:
postgres_1  |
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  |
postgres_1  |
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | waiting for server to start....2018-06-07 14:58:52.404 UTC [38] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2018-06-07 14:58:52.431 UTC [39] LOG:  database system was shut down at 2018-06-07 14:58:49 UTC
postgres_1  | 2018-06-07 14:58:52.437 UTC [38] LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  |
postgres_1  | CREATE ROLE
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | 2018-06-07 14:58:53.128 UTC [38] LOG:  received fast shutdown request
postgres_1  | waiting for server to shut down....2018-06-07 14:58:53.133 UTC [38] LOG:  aborting any active transactions
postgres_1  | 2018-06-07 14:58:53.147 UTC [38] LOG:  worker process: logical replication launcher (PID 45) exited with exit code 1
postgres_1  | 2018-06-07 14:58:53.151 UTC [40] LOG:  shutting down
prisma_1    | Jun 07, 2018 2:58:53 PM org.postgresql.core.v3.ConnectionFactoryImpl log
prisma_1    | WARNING: ConnectException occurred while connecting to postgres:5432
prisma_1    | java.net.ConnectException: Connection refused (Connection refused)
prisma_1    | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
prisma_1    | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
prisma_1    | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
prisma_1    | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
prisma_1    | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
prisma_1    | 	at java.net.Socket.connect(Socket.java:589)
prisma_1    | 	at org.postgresql.core.PGStream.<init>(PGStream.java:69)
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
prisma_1    | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1    | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1    | 	at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1    | 	at org.postgresql.Driver.connect(Driver.java:254)
prisma_1    | 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1    | 	at java.lang.Thread.run(Thread.java:748)
prisma_1    |
prisma_1    | Jun 07, 2018 2:58:53 PM org.postgresql.Driver connect
prisma_1    | SEVERE: Connection error:
prisma_1    | org.postgresql.util.PSQLException: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:245)
prisma_1    | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1    | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1    | 	at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1    | 	at org.postgresql.Driver.connect(Driver.java:254)
prisma_1    | 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1    | 	at java.lang.Thread.run(Thread.java:748)
prisma_1    | Caused by: java.net.ConnectException: Connection refused (Connection refused)
prisma_1    | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
prisma_1    | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
prisma_1    | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
prisma_1    | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
prisma_1    | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
prisma_1    | 	at java.net.Socket.connect(Socket.java:589)
prisma_1    | 	at org.postgresql.core.PGStream.<init>(PGStream.java:69)
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
prisma_1    | 	... 15 more
prisma_1    |
postgres_1  | 2018-06-07 14:58:53.247 UTC [38] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | 2018-06-07 14:58:53.363 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2018-06-07 14:58:53.363 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2018-06-07 14:58:53.370 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2018-06-07 14:58:53.384 UTC [65] LOG:  database system was shut down at 2018-06-07 14:58:53 UTC
postgres_1  | 2018-06-07 14:58:53.479 UTC [1] LOG:  database system is ready to accept connections
postgres_1  | 2018-06-07 14:58:53.763 UTC [72] ERROR:  database "prisma" already exists
postgres_1  | 2018-06-07 14:58:53.763 UTC [72] STATEMENT:  CREATE DATABASE "prisma"
prisma_1    | Obtaining exclusive agent lock...
prisma_1    | Obtaining exclusive agent lock... Successful.
prisma_1    | Deployment worker initialization complete.
postgres_1  | 2018-06-07 14:58:57.753 UTC [93] ERROR:  null value in column "lastPinged" violates not-null constraint
postgres_1  | 2018-06-07 14:58:57.753 UTC [93] DETAIL:  Failing row contains (fd5ae75e-a49c-45cb-81b1-140ef741dafe, null).
postgres_1  | 2018-06-07 14:58:57.753 UTC [93] STATEMENT:  insert into "TelemetryInfo" ("id","lastPinged")  values ($1,$2)
prisma_1    | Initializing workers...
prisma_1    | Successfully started 1 workers.
prisma_1    | Server running on :4466
prisma_1    | Version is up to date.
prisma_1    | [Metrics] Warning: no metrics will be recorded.
prisma_1    | Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
prisma_1    | {"key":"error/handled","requestId":"local:management:cji4o4gp200020a07mprtgjoi","payload":{"exception":"com.prisma.deploy.schema.InvalidProjectId: No service with name 'default' and stage 'default' found","query":"\n      query($name: String! $stage: String!) {\n        project(name: $name stage: $stage) {\n          name\n          stage\n        }\n      }\n    ","variables":"{\"name\":\"default\",\"stage\":\"default\"}","code":"4000","stack_trace":"com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$3(SchemaBuilder.scala:139)\\n scala.Option.getOrElse(Option.scala:121)\\n com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$2(SchemaBuilder.scala:139)\\n scala.util.Success.$anonfun$map$1(Try.scala:251)\\n scala.util.Success.map(Try.scala:209)\\n scala.concurrent.Future.$anonfun$map$1(Future.scala:287)\\n scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)\\n scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)","message":"No service with name 'default' and stage 'default' found"}}
prisma_1    | Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
prisma_1    | Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
prisma_1    | [Debug] Initializing deployment worker for default$default
prisma_1    | [Debug] Scheduling deployment for project default$default
prisma_1    | Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
prisma_1    | Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
prisma_1    | [Debug] Applied migration for project default$default
prisma_1    | Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
prisma_1    | [Metrics] Warning: no metrics will be recorded.
prisma_1    | [Metrics] Warning: no metrics will be recorded.
postgres_1  | 2018-06-07 15:03:54.298 UTC [83] ERROR:  column "data_length" does not exist at character 39
postgres_1  | 2018-06-07 15:03:54.298 UTC [83] STATEMENT:
postgres_1  | 	           SELECT table_schema, sum( data_length + index_length) / 1024 / 1024 FROM information_schema.TABLES GROUP BY table_schema
postgres_1  |
```

**Reproduction**

Create a fresh build with Postgres. Compose file below:

```
version: '3'
services:

  prisma:
    image: prismagraphql/prisma:1.9
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true

  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - "redis-data:/data"

volumes:
  postgres:
  redis-data:
```

**Expected behavior?**

No error to be shown.

**Comment by do4gr** [comment]
Hey,

thanks for reporting. There are 2 issues here:
1. The exceptions in the log are expected. See the comment https://github.com/prismagraphql/prisma/issues/2315#issuecomment-402236025 for details why we designed it this way.
2. The error `column "data_length" does not exist at character 39` is indeed a bug, which we fixed in the latest stable release `1.11`.
