### ISSUE TITLE
database - Connection is not available

### ISSUE THREAD

**Issue by prolink007** [prismagraphql/prisma#2636]
**Describe the bug**
I am following this [guide](https://www.prisma.io/docs/tutorials/setup-prisma/create-new-db/mysql-gui4peul2u) verbatim. I am installing on ubuntu. This is a fresh VM and has nothing already on it. So, i am following the guide exactly. I installed npm and nodejs on the VM.

I am unable to get docker to successfully connect to the database it created and i am unable to get prisma to deploy.

After running `docker-compose up -d`, i get the following output.
```
WARNING: The RFV variable is not set. Defaulting to a blank string.
Creating network "nova_default" with the default driver
Creating volume "nova_mysql" with default driver
Creating nova_prisma_1
Creating nova_mysql_1
```

Running `docker ps` gives me this:
```
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                         PORTS               NAMES
b5c67823b65a        mysql:5.7                  "docker-entrypoint..."   18 minutes ago      Up 18 minutes                  3306/tcp            nova_mysql_1
f04bfd2d0fea        prismagraphql/prisma:1.8   "/bin/sh -c /app/s..."   18 minutes ago      Restarting (1) 3 minutes ago                       nova_prisma_1
```

Running `docker logs` on the prisma container gives me this:
```
Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:18)
	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:439)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:47)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:38)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:218)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:217)
	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:38)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Connection refused (Connection refused)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
	... 14 more

```

Running `docker logs` on the mysql container gives me this:
```
2018-06-15T21:04:55.994925Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-06-15T21:04:55.997545Z 0 [Note] mysqld (mysqld 5.7.22) starting as process 1 ...
2018-06-15T21:04:56.003160Z 0 [Note] InnoDB: PUNCH HOLE support available
2018-06-15T21:04:56.003205Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-06-15T21:04:56.003219Z 0 [Note] InnoDB: Uses event mutexes
2018-06-15T21:04:56.003230Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-06-15T21:04:56.003239Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
2018-06-15T21:04:56.003249Z 0 [Note] InnoDB: Using Linux native AIO
2018-06-15T21:04:56.003552Z 0 [Note] InnoDB: Number of pools: 1
2018-06-15T21:04:56.003709Z 0 [Note] InnoDB: Using CPU crc32 instructions
2018-06-15T21:04:56.005196Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2018-06-15T21:04:56.016823Z 0 [Note] InnoDB: Completed initialization of buffer pool
2018-06-15T21:04:56.022048Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-06-15T21:04:56.033598Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2018-06-15T21:04:56.034652Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 12358492
2018-06-15T21:04:56.034691Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 12358501
2018-06-15T21:04:56.034707Z 0 [Note] InnoDB: Database was not shutdown normally!
2018-06-15T21:04:56.034716Z 0 [Note] InnoDB: Starting crash recovery.
2018-06-15T21:04:56.144245Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2018-06-15T21:04:56.144336Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-06-15T21:04:56.144402Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-06-15T21:04:56.204488Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-06-15T21:04:56.205244Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2018-06-15T21:04:56.205279Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2018-06-15T21:04:56.205830Z 0 [Note] InnoDB: Waiting for purge to start
2018-06-15T21:04:56.255977Z 0 [Note] InnoDB: 5.7.22 started; log sequence number 12358501
2018-06-15T21:04:56.256650Z 0 [Note] Plugin 'FEDERATED' is disabled.
2018-06-15T21:04:56.259992Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2018-06-15T21:04:56.262623Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2018-06-15T21:04:56.264841Z 0 [Note] InnoDB: Buffer pool(s) load completed at 180615 21:04:56
2018-06-15T21:04:56.266704Z 0 [Warning] CA certificate ca.pem is self signed.
2018-06-15T21:04:56.268628Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2018-06-15T21:04:56.270613Z 0 [Note] IPv6 is available.
2018-06-15T21:04:56.270655Z 0 [Note]   - '::' resolves to '::';
2018-06-15T21:04:56.270684Z 0 [Note] Server socket created on IP: '::'.
2018-06-15T21:04:56.272821Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2018-06-15T21:04:56.273773Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2018-06-15T21:04:56.273830Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-06-15T21:04:56.273852Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-06-15T21:04:56.273895Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-06-15T21:04:56.273909Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-06-15T21:04:56.273925Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2018-06-15T21:04:56.275651Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
2018-06-15T21:04:56.278593Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2018-06-15T21:04:56.287151Z 0 [Note] Event Scheduler: Loaded 0 events
2018-06-15T21:04:56.287370Z 0 [Note] mysqld: ready for connections.
Version: '5.7.22'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```

**To Reproduce**
Follow this [guide](https://www.prisma.io/docs/tutorials/setup-prisma/create-new-db/mysql-gui4peul2u) exactly on an ubuntu machine.

My docker-compose.yml file:

```version: '2'
services:
  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: localhost
            port: 3306
            user: root
            password: *******
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: *******
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
```

**Expected behavior**
I would expect docker to connect to the mysql and not get errors in my log files.

**Versions (please complete the following information):**
docker-compose - 1.8.0
node - 4.2.6
npm - 3.5.2
prisma - 1.9.0
ubuntu - 16.04

**Comment by prolink007** [comment]
I was able to get this working. Apparently my password had invalid characters. I changed the password to something different and now it is working.

**Comment by AustinGomez** [comment]
I'm running into this same issue now. I thought it was caused by an invalid password but after changing to alphanumeric there is still the same issue.

**Comment by alexthegoodman** [comment]
@AustinGomez I am also experiencing this issue.

**Comment by AustinGomez** [comment]
@alexthegoodman it seems like it has to do with number of connections. In all it seems that Prisma is unfortunately not production ready. I'm hoping that it will be soon since it's a great tool!

**Comment by paraofheaven** [comment]
@prolink007 I am looking for solution for same issue, could you tell what the answer is?

**Comment by alexthegoodman** [comment]
Consider disabling SSL in the ENV config settings related to the MySQL
database.

**Comment by sanjosedennisns7593** [comment]
Same issue here. Any update on this?

I've been tackling the same issue for a month now, and most of the workaround i found online seem doesn't get work.
