### ISSUE TITLE
(Postgres) Forced to use `CHARACTER VARYING` for id fields?

### ISSUE THREAD

**Issue by stephen-bunn** [prismagraphql/prisma#2662]
**Describe the bug**
_A clear and concise description of what the bug is._

I am unable to get a basic one-to-one relationship query working using Postgres.
This relationship is using `INTEGER` as the id type and the query built is trying to compare `INTEGER` to `CHARACTER VARYING` causing errors when requesting any relationship.

<details>
<summary><b>docker-compose.yml</b> - <i>The docker configration</i></summary>

```yaml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.11-beta
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: $DB_HOST
            port: '5432'
            database: $DB_NAME
            schema: public
            user: $DB_USER
            password: $DB_PASS
            migrations: false
            ssl: true
```
</details>

<details>
<summary><b>create.sql</b> - <i>DDL for the database</i></summary>

```sql
CREATE TABLE location
    (
        id INTEGER NOT NULL,
        description TEXT,
        address CHARACTER VARYING NOT NULL,
        city CHARACTER VARYING,
        state CHARACTER VARYING,
        postal_code CHARACTER VARYING,
        country CHARACTER VARYING,
        PRIMARY KEY(id)
    ) ;
CREATE TABLE account
    (
        id INTEGER NOT NULL,
        name CHARACTER VARYING NOT NULL,
        location_id INTEGER NOT NULL,
        parent_id INTEGER,
        master_id INTEGER,
        PRIMARY KEY(id),
        CONSTRAINT account_parent_id_fkey FOREIGN KEY(parent_id) REFERENCES "account"("id"),
        CONSTRAINT account_master_id_fkey FOREIGN KEY(master_id) REFERENCES "account"("id"),
        CONSTRAINT account_location_id_fkey FOREIGN KEY(location_id) REFERENCES "location"("id"),
        UNIQUE(name)
    ) ;
```
</details>

#### The `datamodel.graphql`

```graphql
type Account @pgTable(name: "account") {
  id: ID! @unique
  name: String!
  master: Account @relation(name: "AccountMaster") @pgRelation(column: "master_id")
  parent: Account @relation(name: "AccountParent") @pgRelation(column: "parent_id")
  location: Location! @relation(name: "AccountLocation") @pgRelation(column: "location_id")
}

type Location @pgTable(name: "location") {
  id: ID! @unique
  description: String
  address: String!
  city: String
  state: String
  postal_code: String
  country: String
}
```

#### The simple query I'm running

```graphql
query {
  accounts {
    id
    name
    location {
      id
      address
    }
  }
}
```

#### The response I was given

```json
{
  "data": {
    "accounts": [
      null,
      null,
      null,
    ]
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:cjim0bm3o006z0a48sgjgx800",
      "path": [
        "accounts",
        0,
        "location"
      ],
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "requestId": "local:api:cjim0bm3o006z0a48sgjgx800"
    },
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:cjim0bm3o006z0a48sgjgx800",
      "path": [
        "accounts",
        1,
        "location"
      ],
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "requestId": "local:api:cjim0bm3o006z0a48sgjgx800"
    },
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:cjim0bm3o006z0a48sgjgx800",
      "path": [
        "accounts",
        2,
        "location"
      ],
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "requestId": "local:api:cjim0bm3o006z0a48sgjgx800"
    }
  ]
}
```

#### The error

```
org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 296
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at com.prisma.api.connector.postgresql.database.PostgresApiDatabaseQueryBuilder.$anonfun$batchSelectAllFromRelatedModel$1(PostgresApiDatabaseQueryBuilder.scala:104)
	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
{"key":"error/unhandled","requestId":"local:api:cjim02712006x0a48n9wf8a4z","clientId":"default$default","payload":{"exception":"org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying\n  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.\n  Position: 296","query":"{\n  accounts {\n    id\n    name\n    location {\n      id\n      address\n    }\n  }\n}\n","variables":"{}","code":"0","stack_trace":"org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)\\n org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)\\n org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)\\n org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)\\n org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)\\n org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)\\n org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)\\n com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)\\n com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)\\n com.prisma.api.connector.postgresql.database.PostgresApiDatabaseQueryBuilder.$anonfun$batchSelectAllFromRelatedModel$1(PostgresApiDatabaseQueryBuilder.scala:104)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)\\n java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n java.lang.Thread.run(Thread.java:748)","message":"ERROR: operator does not exist: integer = character varying\n  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.\n  Position: 296"}}
[Bugsnag - local / testing] Error report: com.bugsnag.Report@69bb712d
```

## NOTE:
**I am able to get this to work** by using `CHARACTER VARYING` as the type for all of my `id` columns in the database. Unfortunately I need to use `INTEGER` or `SERIAL` for the database.

I'm pretty new to graphql in general so there might be a better way to represent the data in the `datamodel.graphql`. Currently, I'm just following the examples provided by the Prisma documentation.

---

**To Reproduce**
1. Create the Prisma docker container using the included `docker-compose.yml` and `datamodel.graphql`
2. Create the database and initialize it with some data
3. `prisma deploy`
4. `prisma playground`
5. Enter in the included query
6. Error is visible in `docker logs <CONTAINER_NAME>`

**Expected behavior**
_A clear and concise description of what you expected to happen._

The built query shouldn't be comparing `integer` to `character varying` when both the specified ids (and `@pgRelation` columns) are `integers`.
Or... if graphql works all in strings then prisma should cast the comparing `integer` to `character varying` for me.

**Finally:** should return results with requested data instead of `null`

**Versions (please complete the following information):**
 - OS: `Ubuntu 18.04 LTS`
 - `prisma` CLI: `prisma/1.10.0 (linux-x64) node-v9.11.1`
 - Prisma Server: `1.11-beta` (I've also tried `1.10` and `1.9`)

**Comment by maarten00** [comment]
+1, I have the exact same problem. Changed all my auto incrementing `id` columns to `CHARACTER VARYING` also fixed it for me, but this seriously stops me from using this in production. Is there another workaround without having to change my database schema?

**Comment by do4gr** [comment]
You don't have to use character varying in this case. You can also the type `Int` for id fields:
```
type MyType {
  id: Int! @unique
}
```
However you also have to change your SQL DDL to auto incrementing keys in that case by using the `SERIAL` type of Postgres. This means it is of type Integer and the database will generate the ids on each insert.
```
CREATE TABLE location
    (
        id SERIAL NOT NULL,
        ...
        PRIMARY KEY(id)
    ) ;
```

**Comment by do4gr** [comment]
I am closing this, but feel free to add more questions.

**Comment by jtwillig** [comment]
I am using `id: Int! @unique` but still get this error when trying to query for location on accounts.

**Comment by saip92** [comment]
Is using Int for ID fields still supported? When I try to do so, I get this error
```
The field `id` is reserved and has to have the format: id: ID! @unique or id: UUID! @unique.
```

**Comment by saip92** [comment]
I'm sorry if it was obvious but I guess `migrations: false` was the thing that I missed.
